<p onclick="alert('Hello');" style="cursor: pointer">
Edunova
</p>
<script>

//https://github.com/tjakopec/OSC3JS
var i={ 
    "employees": [
                 { 
                    "id":           1,
                    "name":         "Admin",  
                    "location":     "USA"
                 },
                 { 
                    "id":           2,
                    "name":         "User",  
                    "location":     "USA"
                 },
                 { 
                    "id":           3,
                    "name":         "User2",  
                    "location":     "USA"
                 }
    ] 
};
for(var j=0;j<i.employees.length;j++){
    console.log(i.employees[j].id);
}



for(var i=0;i<20;i++){
    document.write("Hello");
}
</script>