<body style="background-color:#FFF8DC;">

<div class="container">
    <div class="row">
        <div class="col l6  s12">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5587.073954764354!2d18.67991178184777!3d45.55963920355172!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475ce7a664d75897%3A0xb1a55bac5634fca6!2sEdunova%20-%20U%C4%8Dili%C5%A1te%20informatike%2C%20managementa%20i%20stranih%20jezika!5e0!3m2!1shr!2shr!4v1571692936400!5m2!1shr!2shr" width="400" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        </div>   
            <div class="col l6 s12">
                <h2 class="center-align">Contact us:</h2>
                <div class="row">
                    <form class="col s12">
                        <div class="row">
                            <div class="input-field col m6 s12">
                                <input id="first_name" type="text" class="validate">
                                <label for="first_name">First Name</label>
                            </div>
                            <div class="input-field col m6 s12">
                                <input id="last_name" type="text" class="validate">
                                <label for="last_name">Last Name</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col m6 s12">
                                <i class="mdi-content-mail prefix"></i>
                                <input id="email" type="email" class="validate" required>
                                <label for="email">Email</label>
                            </div>
                            <div class="input-field col m6 s12">
                                <i class="mdi-maps-store-mall-directory prefix"></i>
                                <input id="company" type="text" class="validate">
                                <label for="company">Company</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                            <textarea id="message" class="materialize-textarea"></textarea>
                            <label for="message">Message</label>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col m12">
                            <p class="right-align"><button class="btn btn-large waves-effect waves-light" type="button" name="action">Send Message</button></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>