<body style="background-color:Salmon;">
    <div class="section"></div>
    <main>
      <center>
        <div class="section"></div>    
        <div class="section"></div>
        <div class="container">
          <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">
          <form class="log-in-form" method="post"         
          action="<?php echo App::config("url") ?>index/autoriziraj">       
          <h5 class="indigo-text">Please, login into your account</h5>         
          <div class='row'>      
          <label>Email
            <input type="email" name="email" id="email" 
          <?php if(App::config("dev")) {echo " value=\"dcavajda@edunova.hr\"";}?> />
          </label>  
            <label>Password
            <input type="password" name="password" id="password" 
            <?php if(App::config("dev")) {echo " value=\"edunova\"";}?> />
            </label>   
    <p><?php if(isset($greska)){ echo $greska;} ?></p>
      </form>
      </form>
              <br />
              <center>
                <div class='row'>
                  <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'>Login</button>
                </div>
              </center>
            </form>
          </div>
        </div>
      </center>
      <div class="section"></div>
      <div class="section"></div>
    </main>
</body>

