<body style="background-color:Salmon;">
  <div class="container">
    <div class="row"> 
      <div class="col l3 s12">
        <div class= "center-align">
          <div class="card">
              <div class="card-image">
            <img src="<?php echo App::config("url") ?>public\img\11.jpg">
              <span class="card-title">Charlie Charls</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col l3 s12">
        <div class= "center-align">
          <div class="card">
                <div class="card-image">
                <img src="<?php echo App::config("url") ?>public\img\22.jpg">
                <span class="card-title">Philipe Jomisa</span>
                </div>
                <div class="card-content">
                <p>I am a very simple card. I am good at containing small bits of information.
                I am convenient because I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                <a href="#">This is a link</a>
                </div>
          </div>
        </div>
      </div>
      <div class="col l3 s12">
        <div class= "center-align">
          <div class="card">
            <div class="card-image">
              <img src="<?php echo App::config("url") ?>public\img\33.jpg">
              <span class="card-title">Sarah Mark</span>
            </div>
            <div class="card-content">
                <p>I am a very simple card. I am good at containing small bits of information.
                I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
            <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col l3 s12">
        <div class= "center-align">
            <div class="card">          
              <div class="card-image">
                <img src="<?php echo App::config("url") ?>public\img\44.jpg">
                <span class="card-title">John Jinhichrk</span>
              </div>
              <div class="card-content">
                <p>I am a very simple card. I am good at containing small bits of information.
                    I am convenient because I require little markup to use effectively.</p>
              </div>
              <div class="card-action">
                <a href="#">This is a link</a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  </div>
    <div class="row">
      <div class="col l8 offset-l2 s12 ">
        <div class="card center">
            <div class="card-image ">
                <img src="<?php echo App::config("url") ?>public\img\Ziff_20190213_069-1.jpg">               
                <span class="card-title blue-text text-darken-2">Welcome</span>
            </div>
            <div class="card-content">
            </div>
            <div class="card-panel teal lighten-2">
                <p>Since established in 1995, Law office offers a full range of legal advise and services
                of highest business standards to domestic and international clients.
                We focus our activities on legal consultancy in the fields of corporate & commercial law, 
                M&A, real estate, capital markets, banking & finance, competition law, privatisation, 
                project finance, telecommunications and media law, labor law, intellectual property and dispute resolution.
                For additional information about our Office or in case of your interest for business cooperation, please contact us..</p>
            </div>
            </div>
        </div>
      </div>
    </div>
  
</body>


