<div class="grid-x grid-margin-x">
    <div class="cell large-6 large-offset-3">
        <form method="post" 
            action="<?php echo App::config("url")?>legal_cases/promjeni/<?php echo $id ?>">
                <?php include_once 'detalji.phtml' ?>
                     <div class="row">
                    <div class="col s6">
                            
                                <a class="btn btn-block waves-light"
                                    href="<?php echo App::config("url")?>legal_cases/index">
                                    Back
                                </a>
                            </div>
                            <div>
                            <div class="row">
                             <div class="col s6">
                                <input class="wbtn btn-block white-text waves-light"
                                    type="submit" value="Change legal cases">
                            </div>
                </div>       
        </form>
    </div> 
<div>