<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<script> 
$(document).ready(function(){
    $('.sidenav').sidenav();
  });
</script>

<body>
<nav>
    <div class="nav-wrapper">
    <div>
      <a href="#" data-target="mobile-nav" class="sidenav-trigger">
      <i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">

    
      <li <?php echo Utility::active('/'); //ne radi ?>>
        <a href="<?php echo App::config("url") ?>">
            <?php echo App::config("nazivApp"); ?>
        </a>
      </li>

      <?php if(isset($_SESSION["autoriziran"])): ?>
        <li <?php echo Utility::active('/index/nadzornaPloca'); ?>>
          <a href="<?php echo App::config("url") ?>index/nadzornaPloca">Nadzorna ploča</a>
        </li>
        <li <?php echo Utility::active('/lawyer/index'); ?>>
          <a href="<?php echo App::config("url") ?>lawyer/index">Lawyer</a>
        </li>
        <li <?php echo Utility::active('/client/index'); ?>>
          <a href="<?php echo App::config("url") ?>client/index">Client</a>
        </li>
        <li <?php echo Utility::active('/legal_case/index'); ?>>
          <a href="<?php echo App::config("url") ?>legal_case/index">Legal case</a>
        </li>
        <li <?php echo Utility::active('/legal_trainee/index'); ?>>
          <a href="<?php echo App::config("url") ?>legal_trainee/index">Legal trainee</a>
        </li>
        <li <?php echo Utility::active('/legal_case_trainee/index'); ?>>
          <a href="<?php echo App::config("url") ?>legal_case_trainee/index">Legal case trainee</a>
        </li>
      <?php endif;?>

      <li <?php echo Utility::active('/index/onama'); ?>>
        <a href="<?php echo App::config("url") ?>index/onama">O nama</a>
      </li>
      <li <?php echo Utility::active('/index/kontakt'); ?>>
        <a href="<?php echo App::config("url") ?>index/kontakt">Kontakt</a>
      </li> 
    
      <li>
      <?php if(isset($_SESSION["autoriziran"])): ?>
        <a href="<?php echo App::config("url") ?>index/logout">Odjava
        <?php echo $_SESSION["autoriziran"]->firstnamelastname;?></a>
      <?php else:?>
        <a href="<?php echo App::config("url") ?>index/login">Prijava</a>
      <?php endif;?>
      </li>
    </ul>
  </div>
</div>
     
      
    </ul>
  </div>

  </nav>
  <ul class="sidenav" id="mobile-nav">
  
  <li>
      <?php if(isset($_SESSION["autoriziran"])): ?>
        <a href="<?php echo App::config("url") ?>index/logout">Odjava
        <?php echo $_SESSION["autoriziran"]->firstnamelastname;?></a>
      <?php else:?>
        <a href="<?php echo App::config("url") ?>index/login">Prijava</a>
      <?php endif;?>
      </li>

      <?php if(isset($_SESSION["autoriziran"])): ?>
        <li <?php echo Utility::active('/index/nadzornaPloca'); ?>>
          <a href="<?php echo App::config("url") ?>index/nadzornaPloca">Nadzorna ploča</a>
        </li>
        <li <?php echo Utility::active('/lawyer/index'); ?>>
          <a href="<?php echo App::config("url") ?>lawyer/index">Lawyer</a>
        </li>
        <li <?php echo Utility::active('/client/index'); ?>>
          <a href="<?php echo App::config("url") ?>client/index">Client</a>
        </li>
        <li <?php echo Utility::active('/legal_case/index'); ?>>
          <a href="<?php echo App::config("url") ?>legal_case/index">Legal case</a>
        </li>
        <li <?php echo Utility::active('/legal_trainee/index'); ?>>
          <a href="<?php echo App::config("url") ?>legal_trainee/index">Legal trainee</a>
        </li>
        <li <?php echo Utility::active('/legal_case_trainee/index'); ?>>
          <a href="<?php echo App::config("url") ?>legal_case_trainee/index">Legal case trainee</a>
        </li>
      <?php endif;?>



  </ul>

        
