
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Lawfirm</a>
      <ul class="right hide-on-med-and-down">
      <li>

      <?php if(isset($_SESSION["autoriziran"])): ?>
        <a href="<?php echo App::config("url") ?>index/logout">Odjava
        <?php echo $_SESSION["autoriziran"]->imePrezime;?></a>
      <?php else:?>
        <a href="<?php echo App::config("url") ?>index/login">Prijava </a>
      <?php endif;?>

      </li>
        <li><a href="#">Navbar Link</a></li>
        <li>
        <a href="<?php echo App::config("url") ?>">
            <?php echo App::config("nazivApp"); ?>
        </a>
      </li>
      <li>
        <a href="<?php echo App::config("url") ?>index/onama">O nama</a>
      </li>
      <li>
        <a href="<?php echo App::config("url") ?>index/kontakt">Kontakt</a>
      </li> 
    </ul>
    </ul>
  </div>
      </ul>
      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>

      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>


  <li>
      <?php if(isset($_SESSION["autoriziran"])): ?>

        <a href="<?php echo App::config("url") ?>index/logout">Odjava

        <?php echo $_SESSION["autoriziran"]->imePrezime;?></a>
      <?php else:?>
        <a href="<?php echo App::config("url") ?>index/login">Prijava</a>
      <?php endif;?>
      </li>





      <li>
        <a href="<?php echo App::config("url") ?>">
            <?php echo App::config("nazivApp"); ?>
        </a>
      </li>
      <li>
        <a href="<?php echo App::config("url") ?>index/onama">O nama</a>
      </li>
      <li>
        <a href="<?php echo App::config("url") ?>index/kontakt">Kontakt</a>
      </li> 
    </ul>
  </div>



    </ul>
  </div>
</div>