
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h6 class="white-text">FAIR USE ACT DISCLAIMER </h6>
        <p class="grey-text text-lighten-4">This site is for educational purposes only.</p>
      </div>

      <div class="col l4 offset-l2 s12">
      <h5 class="white-text">link location</h5>
      <ul>
      <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
      </ul>
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
       </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            <div class="callout<?php if(App::config("dev")){echo " alert";} ?>">
               &copy; Edunova <?php echo date("Y"); ?> 
               <?php if(App::config("dev")){echo " DEV";} ?>
 
    </div>
  </div>
</footer>
            
    
        
