
<a href="<?php echo App::config("url") ?>legal_cases/pripremaNovi" 
class="waves-effect waves-light btn center-align">
<i class="material-icons left">add_box</i> Add data</a>
</a>

<fieldset   class="fieldset">      
  <table id="tablicaSmjerovi" >
  <div>
    <h5 class="center-align">Legal cases in your office</h5>
  </div>
    <table id="tablicaSmjerovi"class=striped>
    <thead>
      <tr>
        <th>client:</th>
        <th>legal_case_code:</th>
        <th>case_date_start:</th>
        <th>case_date_end:</th>
        <th>lawyer:</th>
      </tr>
    </thead>
    <tbody>

      
      <?php foreach($legal_cases as $legal_case): ?>
        <tr>
          <td><?php echo $legal_case->client?></td>
          <td><?php echo $legal_case->legal_case_code?></td>
          <td><?php echo $legal_case->case_date_start?></td>
          <td><?php echo $legal_case->case_date_end?></td>
          <td><?php echo $legal_case->lawyer?></td>
          <td>
          <a title="promjeni <?php echo $legal_case->legal_case_code ?>" 
              href="<?php 
              echo App::config("url") 
              ?>legal_cases/pripremaPromjeni/<?php echo $legal_case->legal_case_id ?>">
              <i class="fas fa-edit fa-2x" style="color: orange"></i>
          </a>
            <a title="Obriši <?php echo $legal_case->legal_case_id ?>" 
              onclick="return confirm('Sigurno obrisati <?php echo $legal_case->legal_case_id ?>?');"
              href="<?php 
              echo App::config("url") 
              ?>legal_cases/brisanje/<?php echo $legal_case->legal_case_id ?>">
              <i class="fas fa-trash fa-2x" style="color: red"></i>
              </a>
          </td>
        </tr>
      <?php endforeach;?>
    </tbody>
  </table>
</fieldset>

<style>
ol#smjerovi{
    list-style-type: upper-roman;
}

table#tablicaSmjerovi > tbody > tr > td:nth-child(2),
table#tablicaSmjerovi > tbody > tr > td:nth-child(3),
table#tablicaSmjerovi > tbody > tr > td:nth-child(4),
table#tablicaSmjerovi > tfoot > tr > td:nth-child(1),
table#tablicaSmjerovi > tfoot > tr > td:nth-child(2),
table#tablicaSmjerovi > tfoot > tr > td:nth-child(3)
{
    text-align: left;
}
table#tablicaSmjerovi > tbody > tr > td:nth-child(6)
{
    text-align: left;
}

table#tablicaSmjerovi > thead > tr > th{
    text-align: left;
}
</style>