<form method="post" 

    action="<?php echo App::config("url")?>legal_cases/novi">

    <?php include_once 'detalji.phtml' ?>

        <div class="grid-x">
            <a class="waves-effect waves-light btn"
         href="<?php echo App::config("url")?>legal_cases/index">
            Back to Legal cases

            </a>
            </div>
                <input class="waves-effect waves-light btn"
                type="submit" value="Add new data">
            </div>
        </div>

   
</form>
