<div class="row">
    <div class="col l6 s12">
        <form method="post" 
            action="<?php echo App::config("url")?>legal_cases/promjeni/<?php echo $id ?>">
                <?php include_once 'detalji.phtml' ?> 
                
                    <div class="col l6 s12">
                        <a class="btn btn-block waves-light"
                            href="<?php echo App::config("url")?>legal_cases/index">
                            Back
                        </a>
                    </div>             
                    <div class="col l6 s12">
                            <input class="btn btn-block white-text waves-light"
                            type="submit" value="Change legal cases">
                        
                    </div>  
        </form>
    </div>
    <div class="col l6 s12" id="legal_trainees" >
        <fieldset class="fieldset">
            <legend>Control legal_trainess</legend>
                <input type="text" id="uvjet">
                <table>
                    <thead>
                        <tr>
                            <th>Legal_trainee</th>
                            <th>Akcija</th>
                        </tr>
                    </thead>
                    <tbody id="tijelo">
                        <?php foreach($legal_trainees as $legal_trainee):?>
                            <tr>
                                <td><?php echo $legal_trainee->firstname . " " 
                                . $legal_trainee->lastname ?>
                                
                                <?php echo $legal_trainee->OIB ?>
                                
                                <span style="font-size: 0.7em;">
                                <?php echo $legal_trainee->IBAN ?></span>
                                </td>

                                <td>
                                <a href="#" class="legal_trainee" 
                                id="p_<?php echo $legal_trainee->legal_trainee_id ?>"> 
                                <i class="fas fa-trash fa-2x" style="color: red"></i> 
                                </a></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </fieldset>
        </div>
</div>
