<div class="container">
  <div class="col s2">
    <h5>Your cases for trainees</h5>
    <div class="responsive-table">
      <table id="tablicaSmjerovi">
      
          <thead>
            <tr>
            <th>Legal case</th>
            <th>Legal trainee</th>
            </tr>
          </thead>

          <tbody>
            <?php foreach($legal_case_trainees as $legal_case_trainee): ?>
              <tr>
                <td><?php echo $legal_case_trainee->Legal_case_id?></td>
                <td><?php echo $legal_case_trainee->Legal_trainee_id?></td>
              </tr>
            <?php endforeach;?>
          </tbody>
      </table>
    </div>
  </div>
</div>