<form method="post" 

    action="<?php echo App::config("url")?>clients/novi">

    <?php include_once 'detalji.phtml' ?>

        
            <div class="row">
                <div class="col s6">
            <a class="btn btn-block waves-light"
         href="<?php echo App::config("url")?>clients/index">
            Back to clients
            </a>
            </div>

            <div class="row">
                <div class="col s6">
                <input class="btn btn-block white-text waves-light "
                type="submit" value="Add new client">
            </div>
        

</form>

