<fieldset class="fieldset">
    <legend>Popunite tražene podatke</legend>

        <?php echo Utility::inputText(
         isset($greska) ? $greska : null,'firstname','firstname');?>
        <?php echo Utility::inputText(
          isset($greska) ? $greska : null,'lastname','lastname');?>
        <?php echo Utility::inputText(
          isset($greska) ? $greska : null,'IBAN','IBAN');?>
         <?php echo Utility::inputText(
         isset($greska) ? $greska : null,'OIB','OIB');?>

</fieldset>
<hr />
