<fieldset class="fieldset">
    <legend>Popunite tražene podatke</legend>

        <?php echo Utility::inputText(
         isset($greska) ? $greska : null,'firstname','firstname');?>
        <br />
        <?php echo Utility::inputText(
          isset($greska) ? $greska : null,'lastname','lastname');?>
        <br />
        <?php echo Utility::inputText(
          isset($greska) ? $greska : null,'IBAN','IBAN');?>
        <br />
         <?php echo Utility::inputText(
         isset($greska) ? $greska : null,'OIB','OIB');?>
</fieldset>
         <br />


