<a href="<?php echo App::config("url") ?>clients/pripremaNovi" 
class="btn-centre btn-small waves-effect waves-light red">
<i class="material-icons">add</i>
</a>Add new client</a>

<div class="container">
  <div class="col s2">
    <h5>Clients in your office</h5>
    <div class="responsive-table">
      <table id="tablicaSmjerovi">
          <thead>
            <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>OIB</th>
            <th>IBAN</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($clients as $client): ?>
              <tr>
                <td><?php echo $client->firstname?></td>
                <td><?=$client->lastname?></td>
                <td><?php echo $client->OIB?></td>
                <td><?php echo $client->IBAN?></td>
              </tr>
            <?php endforeach;?>
          </tbody>
      </table>
    </div>
  </div>
</div>

<td>

  <a title="Promjeni 
  <?php echo $client->firstname ?>
  <?php echo $client->lastname ?>
  <?php echo $client->IBAN ?>
  <?php echo $client->OIB ?>"    
    href="<?php echo App::config("url") ?> client/pripremaPromjena/ <?php echo $client->client_id ?>">

    <i class="fas fa-edit fa-2x" style="color: orange"></i>

  </a>

              <a title="Obriši 
              <?php echo $client->firstname ?>
              <?php echo $client->lastname ?>
              <?php echo $client->IBAN?>
              <?php echo $client->OIB ?>" 

                  href="<?php 
                  echo App::config("url") 
                  ?>client/brisanje/<?php echo $client->client_id ?>">

                  <i class="fas fa-trash fa-2x" style="color: red"></i>

              </a>      
        
</td>