<a href="<?php echo App::config("url") ?>clients/pripremaNovi" 

class=" button expanded">
<i class="fas fa-plus-square"></i>
Dodaj novi smjer</a>


<div class="container">
  <div class="col s2">
    <h5>Clients in your office</h5>
    <div class="responsive-table">
      <table id="tablicaSmjerovi">
          <thead>
            <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>OIB</th>
            <th>IBAN</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($clients as $client): ?>
              <tr>
                <td><?php echo $client->firstname?></td>
                <td><?=$client->lastname?></td>
                <td><?php echo $client->OIB?></td>
                <td><?php echo $client->IBAN?></td>
              </tr>
            <?php endforeach;?>
          </tbody>
      </table>
    </div>
  </div>
</div>