<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<script> 
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
      direction:'right'
    });
  });
</script>
<div class="fixed-action-btn" style="top: 80px; left: 15px;">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
    <li>
       
      <a class="btn-floating red"><i class="material-icons">delete</i></i></a></li>
        

      <li><a class="btn-floating yellow darken-1"><i class="material-icons">update</i></a></li>

      <a href="<?php echo App::config("url") ?>clients/pripremaNovi" 
      <a class="btn-floating blue"><i class="material-icons">fiber_new</i></a></li>

    </ul>
  </div>
      
<div class="container">
  <div class="col s2">
    <br>
    <br>
    <h5>Clients in your office</h5>
    <div class="responsive-table">
      <table id="tablicaSmjerovi">
          <thead>
            <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>OIB</th>
            <th>IBAN</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($clients as $client): ?>
              <tr>
                <td><?php echo $client->firstname?></td>
                <td><?=$client->lastname?></td>
                <td><?php echo $client->OIB?></td>
                <td><?php echo $client->IBAN?></td>
              </tr>
            <?php endforeach;?>
          </tbody>
      </table>
    </div>
  </div>
</div>

<td>

  <a title="Promjeni 
  <?php echo $client->firstname ?>
  <?php echo $client->lastname ?>
  <?php echo $client->IBAN ?>
  <?php echo $client->OIB ?>"    
    href="<?php echo App::config("url") ?> client/pripremaPromjena/ <?php echo $client->client_id ?>">

    <i class="fas fa-edit fa-2x" style="color: orange"></i>

  </a>

              <a title="Obriši 
              <?php echo $client->firstname ?>
              <?php echo $client->lastname ?>
              <?php echo $client->IBAN?>
              <?php echo $client->OIB ?>" 

                  href="<?php 
                  echo App::config("url") 
                  ?>client/brisanje/<?php echo $client->client_id ?>">

                  <i class="fas fa-trash fa-2x" style="color: red"></i>

              </a>      
        
</td>