<div class="grid-x grid-margin-x">
    <div class="cell large-6 large-offset-3">
        <form method="post" 
            action="<?php echo App::config("url")?>clients/novi">
            
            <fieldset   class="fieldset">
                <legend>Popunite tražene podatke</legend>
                <label>
                    Firstname
                    <input type="text" id="firstname" name="firstname">
                </label>

                <label>
                    Lastname
                    <input type="text" id="lastname" name="lastname">
                </label>

                <label>
                    IBAN
                    <input type="text" id="IBAN" name="IBAN">
                </label>

                <label>
                    OIB
                    <input type="text" id="OIB" name="OIB">
                </label>

                
                <hr />
                <div class="grid-x">

                    <div class="large-8 small-6 column">
                        <input class="button expanded"
                            type="submit" value="Dodaj novi">
                    </div>

                    <div class="large-3 small-5 column">
                        <a class="button expanded"
                            href="<?php echo App::config("url")?>clients/index">
                            Odustani
                        </a>
                    </div>


                </div>
            </fieldset>
        </form>
    </div>
</div>