<form method="post" 
    action="<?php echo App::config("url")?>clients/novi">
            
            <fieldset   class="fieldset">
                <legend>Add new client</legend>
                <label>
                    Firstname
                    <input type="text" id="firstname" name="firstname">
                </label>

                <label>
                    Lastname
                    <input type="text" id="lastname" name="lastname">
                </label>

                <label>
                    IBAN
                    <input type="text" id="IBAN" name="IBAN">
                </label>

                <label>
                    OIB
                    <input type="text" id="OIB" name="OIB">
                </label>

                
                <hr />
                <div class="grid-x">

                    <div class="large-8 small-6 column">
                        <input class="button expanded"
                            type="submit" value="Add new">
                    </div>
                        <br>
                    <div class="large-8 small-6 column">
                        
                        <a href="<?php echo App::config("url")?>clients/index">
                        <input class="button expanded"
                        type="submit" value="Back to Clients">
                        </a>
                    </div>
                </div>
    </fieldset>
</form>
