<form method="post" 

    action="<?php echo App::config("url")?>clients/novi">

    <?php include_once 'detalji.phtml' ?>

        <div class="grid-x">
            <a class="btn btn-block waves-effect waves-light"
         href="<?php echo App::config("url")?>clients/index">
            Back to clients

            </a>
            </div>
                <input class="btn btn-block waves-effect waves-light"
                type="submit" value="Add new client">
            </div>
        </div>

   
</form>
<style>
.btn-block {
    width: 100%;
}
</style>
