<div class="grid-x grid-margin-x">
    <div class="cell large-6 large-offset-3">
        <form method="post" 
            action="<?php echo App::config("url")?>clients/promjeni/<?php echo $id ?>">
                <?php include_once 'detalji.phtml' ?>
                    <div class="grid-x">
                            <div>
                                <a class="btn btn-block waves-effect waves-light"
                                    href="<?php echo App::config("url")?>clients/index">
                                    Back
                                </a>
                            </div>
                            <div>
                                <input class="btn btn-block waves-effect waves-light"
                                    type="submit" value="Change client">
                            </div>
                    </div>
            
        </form>
    </div> 
<div>

<style>
.btn-block {
    width: 100%;
}
</style>