<div class="row">
  <div class="col l8 offset-l2 s12 ">
      <fieldset class="fieldset">
          <legend>Popunite tražene podatke</legend>
              <?php echo Utility::inputText(
              isset($greska) ? $greska : null,'firstname','firstname');?>
              <br />
              <?php echo Utility::inputText(
                isset($greska) ? $greska : null,'lastname','lastname');?>
              <br />
              <?php echo Utility::inputText(
                isset($greska) ? $greska : null,'email','email');?>
              <br />
              <?php echo Utility::inputText(
              isset($greska) ? $greska : null,'uloga','uloga');?>
      </fieldset>
     
  </div>
</div>