<a href="<?php echo App::config("url") ?>lawyers/pripremaNovi" 
class="waves-effect waves-light btn center-align">
<i class="material-icons left">add_box</i> Add new lawyer</a>
</a>
<div id="container">
  <div class="row">
        <?php foreach($lawyers as $lawyer): ?>
          <div class="col s12 m4 grey lighten-4">
            <div class= "center-align">
              <div class="card">
                <div class="card-content">
                    <div class="card-title teal accent-4 black-text">
                    <h5>Lawyer information</h5>
                    </div>
                    <img src="<?php echo App::config("url") ?>public/img/nepoznataOsoba.png">
                    <ul class="collection">
                    
                    
                    <li><?php echo $lawyer->firstname?></li>
                    <li><?php echo $lawyer->lastname?></li>
                    <li><?php echo $lawyer->OIB?></li>
                    <li><?php echo $lawyer->IBAN?></li>
                    </ul>

                      <div>
                    
                      <a title="Obriši <?php echo $lawyer->lawyer_id ?>" 
                      onclick="return confirm('Sigurno obrisati <?php echo $lawyer->lawyer_id ?>?');"
                      href="<?php 
                      echo App::config("url") 
                      ?>lawyers/brisanje/<?php echo $lawyer->lawyer_id ?>">
                      <div class="btn btn-block btn-large red accent-2">Delete lawyer</div>

                      <a title="promjeni <?php echo $lawyer->firstname ?>" 
                      href="<?php echo App::config("url")?>lawyers/pripremaPromjeni/
                      <?php echo $lawyer->lawyer_id ?>">
                      <div class="btn btn-block btn-large yellow accent-4">Change information</div>
                         
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php endforeach;?>  
  </div>
</div>


<style>
#container
{
    margin-top:15px;
}
.card-content {
    text-align: center; 
    padding: 0px !important;
}
.card{
    transition: .5s;
}
.card:hover{
    transform:scale(1.05);
}
</style>