<form method="post" 

    action="<?php echo App::config("url")?>lawyers/novi">

    <?php include_once 'detalji.phtml' ?>

        <div class="grid-x">
            <a class="waves-effect waves-light btn"
         href="<?php echo App::config("url")?>lawyers/index">
            Back to lawyers

            </a>
            </div>
                <input class="waves-effect waves-light btn"
                type="submit" value="Add new Lawyer">
            </div>
        </div>

</form>
