<form method="post" 

    action="<?php echo App::config("url")?>lawyers/novi">

    <?php include_once 'detalji.phtml' ?>

        <div class="grid-x">
            <a class="btn btn-block waves-effect waves-light"
         href="<?php echo App::config("url")?>lawyers/index">
            Back to lawyers

            </a>
            </div>
                <input class="btn btn-block waves-effect waves-light"
                type="submit" value="Add new Lawyer">
            </div>
        </div>

</form>
<style>
.btn-block {
    width: 100%;
}
</style>