
<form method="post" 
     action="<?php echo App::config("url")?>legal_trainees/promjeni/<?php echo $id ?>">
        <?php include_once 'detalji.phtml' ?>
        <div class="row">
            <div class="col s6">
            <a class="btn btn-block waves-light"
           href="<?php echo App::config("url")?>legal_trainees/index"> Back
            </a>
        </div>
            
            <div class="row">
            <div class="col s6">
            <input class="btn btn-block white-text waves-light "
            type="submit" value="Change Legal trainee">
            </div>
     </div>
            
</form>

